### ISSUE TITLE
Replace this code at WinMain() to enable memory checks on windows builds.

### ISSUE THREAD

**Issue by GoldSciences** [SaschaWillems/Vulkan#111]
Replace this:

```
#if defined(__ANDROID__)
    // Removing this may cause the compiler to omit the main entry point 
    // which would make the application crash at start
    app_dummy();
#endif
```

With this:

```
#if defined(__ANDROID__)
    // Removing this may cause the compiler to omit the main entry point 
    // which would make the application crash at start
    app_dummy();
#elif defined(_WIN32)
#if defined(DEBUG) || defined(_DEBUG)
    _CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_CHECK_CRT_DF | _CRTDBG_DELAY_FREE_MEM_DF | _CRTDBG_LEAK_CHECK_DF); //_CRTDBG_CHECK_ALWAYS_DF)
#endif
#endif
```

**Comment by SaschaWillems** [comment]
Thx for pointing me at this. Will this work with non-Microsoft Compiler too?

**Comment by GoldSciences** [comment]
Good question. Actually I've never tried it outside VS , so if you find out please let me know.

**Comment by 1ace** [comment]
The [MSDN](https://msdn.microsoft.com/en-us/library/5at7yxcs.aspx) page might be of interest.
Note that all I know comes from 10min of googling, but I believe this is an MS-specific extension, available only on `msvc`.

As for the suggested code itself, it's doing something completely unrelated to the Android `app_dummy()` hack, so it doesn't belong in the same code block, and should be its own block IMHO. I also don't understand the point of the second level `#if` in the `#elif`?

**Comment by GoldSciences** [comment]
That's correct. The nested if/endif block may be pointless as _CrtSetDbgFlag() may do nothing for release builds, though it may compile with no error anyway. It's just a reminder that the code won't do anything on release builds.

For the msvc thing, the thing is that if you use other libs such as mingw, they may still use the msvc runtime under te covers, so it would work anyway. The flags apply to allocations done by the ms memory manager, which is something other compilers may still rely on.

**Comment by GoldSciences** [comment]
Turns out that when I build Android apps under Visual Studio I still have _WIN32 defined, so making it part of the #ifdef (ANDROID) makes that it doesn't try to compile that line for Android apps. This happens also when trying to build linux apps in VS so I always do:
```
#if defined(ANDROID)
#elif defined(__linux__)
#elif defined(_WIN32)
#else 
// default for unknown platforms
#endif 
```
In that order.

**Comment by 1ace** [comment]
> Turns out that when I build Android apps under Visual Studio I still have _WIN32 defined

That doesn't sound right. I'd say your toolchain is broken, but since you're using `msvc` that's already a well-known fact :stuck_out_tongue_closed_eyes:

Seriously though, that shouldn't be possible. When cross-compiling, only the defines for the target architecture should be defined, otherwise everything project would break and have to be made aware of where it's being built from as well, which would just be a nightmare.

**Comment by GoldSciences** [comment]
Actually I believe if you build for Android you will have __linux__ defined too.

**Comment by SaschaWillems** [comment]
That's true, as Android contains a Linux kernel ;)

**Comment by GoldSciences** [comment]
Though most linux developers I know won't hesitate to clarify about android linux: "that's not a true linux". Well, _WIN32 is a flag telling you're using the VS compiler, not that your app is targeted to Windows: note that also for x64 builds you will have the _WIN32 defined, when it's actually not 32 bit at all. For targeting Windows platforms the proper flag you should use is WIN32 -without the underscore- and you should probably declare it yourself, as _WIN32 is intended mostly for the implementation of the compiler libraries.

**Comment by 1ace** [comment]
> android linux: "that's not a true linux"

Android Linux is not GNU/Linux, but it's still Linux. It's a different userspace, but the kernel is the same (with some patch, most of which are being upstreamed).


> _WIN32 is a flag telling you're using the VS compiler, not that your app is targeted to Windows

That's not how the rest of the world interprets it :]
https://en.wikipedia.org/wiki/Cross_compiler


> for x64 builds you will have the _WIN32 defined

That's the result of a bad decision from Microsoft, it has nothing to do with the standards. If they had named it `__windows__` instead of `_WIN32` and used something else to declare the word size, it wouldn't have been a problem for them.
Almost everyone else made the right choice for this btw: https://sourceforge.net/p/predef/wiki/OperatingSystems/


> For targeting Windows platforms the proper flag you should use is WIN32 -without the underscore- and you should probably declare it yourself, as _WIN32 is intended mostly for the implementation of the compiler libraries.

I've never heard that, but then again my interaction with Windows developers is minimal. It would come down to preferences anyway, and knowing Windows devs they probably wouldn't all agree :smirk:
*(For instance, at ImgTec (where I work), the Windows team defines `WINDOWS`)*

**Comment by GoldSciences** [comment]
But isn't the single underscore reserved to implementation of the compiler? In such case, __linux__ would be for use by "the user", while _WIN32 would be a private macro for the compiler libraries themselves, so they can call it whatever they want.

**Comment by 1ace** [comment]
No, what is reserved is defining those macros. Anyone can use them (that's the whole point).

**Comment by GoldSciences** [comment]
But you're complaining about the wrong decisions of MS but still relying on those decisions for your program. In my opinion one would be much better defining `__windows__ ` oneself and just making use of that define, instead of relying on bad defines born from bad decisions that are incosistent and don't represent what's actually being built (such as 64-bit apps targeting 64-bit or Windows Phone apps)

**Comment by GoldSciences** [comment]
Ah sorry I missed that part. It seems ImgTec guys are smart about it and defined it themselves.

**Comment by SaschaWillems** [comment]
Been testing around with _CrtSetDbgFlag and with the examples I tested I didn't find any memory leaks. Since this is MSVC specific I'm not going to add this for all examples.
