### ISSUE TITLE
Dynamically using the Vulkan Loader library

### ISSUE THREAD

**Issue by HarryLovesCode** [SaschaWillems/Vulkan#130]
I happened to stumble upon the series about Vulkan called "API without Secrets". In part 1, they say the following:

> There are several ways to use the Vulkan API in our application:

> 1. We can dynamically load the driver’s library that provides Vulkan API implementation and acquire function pointers by ourselves from it.
- We can use the Vulkan SDK and link with the provided Vulkan Runtime (Vulkan Loader) static library.
- We can use the Vulkan SDK, dynamically load Vulkan Loader library at runtime, and load function pointers from it.

> The first approach is not recommended. Hardware vendors can modify their drivers in any way, and it may affect compatibility with a given application. It may even break the application and require developers writing a Vulkan-enabled application to rewrite some parts of the code. That’s why it’s better to use some level of abstraction. - [Source](https://software.intel.com/en-us/api-without-secrets-introduction-to-vulkan-part-1#_Toc445674436)

However, I'm not sure if that's true because I thought Vulkan implementations were required to pass conformance tests. Any thoughts?

**Comment by SaschaWillems** [comment]
> However, I'm not sure if that's true because I thought Vulkan implementations were required to pass conformance tests

No, that's no requirement. You only have to pass conformance tests if you want your implementation to be listed on the official Khronos page. An IHV that doesn't care about this is free to release a nonconformant Vulkan implementation.

My Android examples use the first way as Vulkan is not a part of the OS image on the device I'm testing with (or any other Android device), so that's the only way of using Vulkan there. So that passage from the Intel series may only be valid for platforms like Windows and Linux anyway.

**Comment by eloj** [comment]
I don't know what conformance covers, but I doubt it covers the parts below the loader. I think the point with (1) is that an IHV could for instance change the name/location of the actual library at any point without breaking conformance, so you shouldn't try to load "vulkan-1.dll" and expect that to work going forward.

**Comment by HarryLovesCode** [comment]
Got it thanks for the clarification!
