### ISSUE TITLE
Problem with Skeletal Animation

### ISSUE THREAD

**Issue by MichaelWei1990** [SaschaWillems/Vulkan#150]
It looks like the skeletal animation sample can only work for the Astro Boy model as the animation is horribly wrong when loading other animated models, which have been tested on Blender. I think the cause could be the issue of the skinning matrix (mOffsetMatrix) defined in aiBone struct in Assimp, as its values are quite different from the one contained in .dae file. This may not have to be Vulkan's problem but would you please double check this issue or contact the publisher of Assimp for solutions, that would be very kind of you.

**Comment by SaschaWillems** [comment]
I'll push an updated version of this example soon that has been overhauled in a few aspects. It also uses a different mesh and works fine.

The problem seems to be blender, as none of the models I exported from blender had working animations. Exporting from e.g. 3ds max (using the COLLADA exporter) produces a model with animations that work and look fine.

But if you can confirm that this is a bug with ASSIMP, feel free to open up an issue at their github repository.
