### ISSUE TITLE
fold transitions into renderpass

### ISSUE THREAD

**Issue by ratchetfreak** [SaschaWillems/Vulkan#155]
https://github.com/SaschaWillems/Vulkan/blob/master/base/vulkanexamplebase.cpp#L1571

If you set the initialLayout to UNDEFINED and the finalLayout to Present (while keeping the subpass reference to COLOR_ATTACHMENT_OPTIMAL). And add dependencies from EXTERNAL to 0 and 0 to EXTERNAL with the correct masks. Then you can remove the pre and post present vkCmdPipelineBarrier calls as the renderpass will transition the attached images as required.

**Comment by SaschaWillems** [comment]
Sorry for the long delay, this kinda got lost until I was asked about the present barriers today. 

So thanks for hinting me at the directions :+1:  

I already have this up and working in the triangle example and will check if it works on all the implementations I have here to test. If it works as expected I'll add this to the other samples too, push the changes and maybe do a small write up on how this actually works as it seems that most of the samples also use dedicated barriers instead of the sub pass dependencies along with the layouts.

**Comment by Overv** [comment]
Is the explicit render pass dependency necessary? The specification seems to implicitly create this dependency if no dependencies are specified and the alias flag is not passed.

**Comment by SaschaWillems** [comment]
I just read over the current specs (1.0.20) and did not see anything that hints at an implicit dependency, so I'd say yes it's actually necessary (unless you do manual barriers).

**Comment by ratchetfreak** [comment]
@SaschaWillems actually:

> * If the attachment does not include the `VK_ATTACHMENT_DESCRIPTION_MAY_ALIAS_BIT` bit and there is no subpass dependency from `VK_SUBPASS_EXTERNAL` to the first subpass that uses the attachment, then it is **as if there were such a dependency** with `srcStageMask = srcAccessMask = 0` and `dstStageMask` and `dstAccessMask` including all relevant bits (all graphics pipeline stages and all access types that use image resources), with the transition executing as part of that dependency. In other words, it may overlap work before the render pass instance and is complete before the subpass begins.

The explicit EXTERNAL to 0 dependency is necessary because the implicit pre-renderpass transition without the dependency is implicitly with a barrier from top-of-the-pipe (it says 0 but logically it's top) while you need it to be from whatever waitStage you set the acquire semaphore to.

In the optimal case that stage will be COLOR_ATTACHMENT_OUTPUT because that is the only other thing that needs to wait until the image is free to be used. 

Though the 0 to EXTERNAL isn't necessary because the implicit post-renderpass transition is to bottom of the pipe and the semaphore that gets signaled from that command buffer will only get signaled after all work is done (including those transitions) aka bottom-of-the-pipe.

**Comment by SaschaWillems** [comment]
@ratchetfreak : Thx :+1:  I'm at work right now so I only had time for a quick look and missed that part.

**Comment by Overv** [comment]
Would the dependency look something like this?

```
VkSubpassDependency dependency = {};
dependency.srcSubpass = VK_SUBPASS_EXTERNAL;
dependency.dstSubpass = 0;
dependency.srcStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
dependency.dstStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
dependency.srcAccessMask = 0;
dependency.dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
dependency.dependencyFlags = 0;
```

I'm not entirely sure about the source stage and access mask because presentation is not part of the graphics pipeline.

**Comment by SaschaWillems** [comment]
I'm at work, so I can't check but out of my head these one should do it (and pass validation). I use them in the updated triangle example (sorry, haven't had the time yet to upload that one).

Initial (which is necessary):

    dependency.srcSubpass = VK_SUBPASS_EXTERNAL;
    dependency.dstSubpass = 0;
    dependency.srcStageMask = VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT;
    dependency.dstStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
    dependency.srcAccessMask = VK_ACCESS_MEMORY_READ_BIT;
    dependency.dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_READ_BIT | VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;

Final (not necessary due to implicit dependency):

	dependency.srcSubpass = 0;
    dependency.dstSubpass = VK_SUBPASS_EXTERNAL;
    dependency.srcStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
    dependency.dstStageMask = VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT;
    dependency.srcAccessMask = VK_ACCESS_COLOR_ATTACHMENT_READ_BIT | VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
    dependency.dstAccessMask = VK_ACCESS_MEMORY_READ_BIT;

**Comment by ratchetfreak** [comment]
I wouldn't blindly trust validation on this quite yet, the synchronization validation is still quite incomplete.

**Comment by SaschaWillems** [comment]
> I wouldn't blindly trust validation on this quite yet, the synchronization validation is still quite incomplete.

That's right and why I did test these dependencies on NVIDIA (Windows and Android), AMD and Intel and they worked on all of them. So I guess they're okay :wink:

**Comment by SaschaWillems** [comment]
Finally got around replacing the explicit image layout transitions for the attachments in my triangle example. 

They're now folded into the render pass using subpass dependencies. I tried to comment as much as possible ([see the setupFrameBuffer function](https://github.com/SaschaWillems/Vulkan/blob/master/triangle/triangle.cpp#L734). If some of the comments don't make sense then it's probably because it's late at night over here ;)

I'll now start on replacing the explicit transitions for the base class and the other examples too.

Thanks again @ratchetfreak, folding them into the renderpasses makes the code look cleaner and once you get how this works you start to realize how cool that feature is :wink:

**Comment by SaschaWillems** [comment]
Update base classes and all examples to use sub passes for layout transitions instead of explicit barriers.
