### ISSUE TITLE
pipelines.cpp uses wide lines feature without enabling it

### ISSUE THREAD

**Issue by jherico** [SaschaWillems/Vulkan#165]
Pipelines.cpp doesn't enable the wide lines feature, nor does it add line width to the dynamic state enables.  Adding the dynamic state flag causes the line width to work, but I still get validation errors because during device creation wide lines was not enabled.  

This is a tricky fix because it requires a `PhysicalDeviceFeatures` pointer to be passed into the `DeviceCreateInfo` structure during the call to `vkCreateDevice`, but this call happens in the constructor for the base class, so the individual example classes can't modify the input parameters.  It's may not be desirable to pass in the results of `vkGetPhysicalDeviceFeatures` as enabling all the available features whether you plan to use them or not might impact performance.  

I've made a change locally by adding an additional optional VkPhysicalDeviceFeatures parameter to VulkanExampleBase in which I can pass a statically statically initialized structure that has wide lines enabled, and this quiets validation, but I don't know if it's a good general purpose approach.

**Comment by SaschaWillems** [comment]
I noticed that too. My initial idea was the same as yours, but I think I'll go with a virtual function in the base class that can be used in the derived example to pass a custom physical device feature set. Adding something to the base class (constructor) would require a change to all examples, and since there are already several virtual functions in the base class that can be derived I think that's the better choice.

I also think that's a bit cleaner and as future examples may require other physical device features to be enabled I guess I'll go with this one.

**Comment by jherico** [comment]
A virtual function wont work.  The device is created in the base class
ctor.  when a virtual function resolves in a ctor, the derived class
doesn't exist yet, so it would always call the base class version.

**Comment by SaschaWillems** [comment]
Ah well, then I'll have to go with another solution.
