### ISSUE TITLE
Sample: Multi-primitive type rendering

### ISSUE THREAD

**Issue by Nikolsi** [SaschaWillems/Vulkan#182]
Hello, may I ask you how to render objects with different PrimitiveTopology setting in the same pipeline? For example, I want to render a surface made with triangles and then lines over, thus there will be two different topologies in the same scene.

Could give me an advice how should I change settings and recreate InputAssemblyStateCreateInfo, but it is too heavy, I think and not efficient. Or do you have an example with that or could you prepare something like this?

Thank you in advance.

**Comment by SaschaWillems** [comment]
The primitive topology is part of the pipeline state object and you simply can't change it for that pipeline after it has been created.

So you have to create different pipelines for the different topology types you need. And don't worry about performance, that's why PSOs exists. Switching between them is very fast, and if you use pipeline derivatives performance will be fine.

As pipelines are created only once and command buffers often remain static this is actually pretty fast.

**Comment by Nikolsi** [comment]
Thank you for such a quick response,
Do you mean to prepare several pipelines for rendering different topologies and just submit it when certain is needed, right?
And they will overlap each other, thus could I see all of them at the same time in a scene?
Thank you

**Comment by SaschaWillems** [comment]
Yes, you are free to switch pipelines during your render pass. Attachments are only cleared between render passes.

Note that I'll be closing this issue. If you have additional questions on Vulkan freel free to ask on stackoverflow or the official Khronos forums. I'm active on both.
