### ISSUE TITLE
About triangle example several issues.

### ISSUE THREAD

**Issue by Qjames** [SaschaWillems/Vulkan#199]
Hi,
I noticed that in triangle.cpp file, line:745
`vkTools::setImageLayout` with setupCmdBuffer parameter, but it is not flushed indeeded.
Also, this part seemed is not needed, since you have write the barrier in layoutcmd.

Btw, when I build android apk from windows, tsome can ran correctly while others are crashed in different libraries.
I'm using ant-1.9.2, and ndk11 for windows, android sdk 23/24, java 1.8,  can you help tell me which you used?
Thanks very much.

**Comment by SaschaWillems** [comment]
> I noticed that in triangle.cpp file, line:745
vkTools::setImageLayout with setupCmdBuffer parameter, but it is not flushed indeeded.
Also, this part seemed is not needed, since you have write the barrier in layoutcmd.

Yes, the setImageLayout is a left-over and makes no sense. Will remove that one.

> Btw, when I build android apk from windows, tsome can ran correctly while others are crashed in different libraries.
I'm using ant-1.9.2, and ndk11 for windows, android sdk 23/24, java 1.8, can you help tell me which you used?

I build against SDK level 19 (see _setup.bat in android sub folder) using the latest NDK (11g afair). Can you add some details? Do the samples crash or the build process? Updating to the latest SDK level is on my todo list.

**Comment by Qjames** [comment]
Triangle is ok now. I re set my build environment.
Thanks for your help.
