### ISSUE TITLE
Why not OIT?

### ISSUE THREAD

**Issue by acterhd** [SaschaWillems/Vulkan#2]
Hello. Why there is no Order Independent Transparency example?

**Comment by SaschaWillems** [comment]
Because I haven't done anything in that area (yet). I do these examples in my spare time, so I don't have that much time to work on them.

If you want to see an example for a certain technique (like OIT), please feel free to open up a feature request once the examples go live.

Right now I don't have plans to release an OIT example.

**Comment by acterhd** [comment]
When I can use Vulkan API?
4 янв. 2016 г. 22:01 пользователь "Sascha Willems" <notifications@github.com>
написал:

**Comment by SaschaWillems** [comment]
As soon as the SDK (and drivers for the GPU you use) are available. Vulkan didn't make it in 2015. See the Khronos Working Group status update for details : https://www.khronos.org/vulkan

**Comment by acterhd** [comment]
Why not make ray tracing example?
