### ISSUE TITLE
C++14 required, not C++11

### ISSUE THREAD

**Issue by schwa423** [SaschaWillems/Vulkan#235]
Contrary to README.md, this repo requires C++14 to build.

The dependencies on C++14 are extremely minimal... to build for C++11, I need to make only two changes:
- replace "14" with "11" in the top-level CMakeLists.txt
- replace the use of std::make_unique<> in base/threadpool.hpp

**Comment by SaschaWillems** [comment]
This has (partially) been discussed in #167 and I'm aware of this. The C++11 requirement was before I added the multi threading demo.

My plan is to support C++11 rather than updating the requirements, so a broader audience can compile my examples.

Don't know when I'll find the time to fix this though.

**Comment by SaschaWillems** [comment]
I just pushed a fix for this. Implemented make_unique (as per Herb Sutters' blog post) and fixed the flags in the CMakeLists.txt

Worked fined here on windows using MinGW.

Can you check with your configuration and see if the examples now compile for you?

**Comment by schwa423** [comment]
Works fine for me, thanks!
