### ISSUE TITLE
Bad layout for shader image acess in shadowmapping demo

### ISSUE THREAD

**Issue by scyganINTEL** [SaschaWillems/Vulkan#253]
```
		// Image descriptor for the shadow map attachment
		VkDescriptorImageInfo texDescriptor =
			vkTools::initializers::descriptorImageInfo(
				offscreenPass.depthSampler,
				offscreenPass.depth.view,
				VK_IMAGE_LAYOUT_GENERAL);
```

Above code in shadowmapping.cpp is wrong, as depth image is not in GENERAL layout. It was transitioned to SHADER_READ_ONLY_OPTIMAL at the end of the renderpass.

```
attchmentDescription.finalLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;      // Attachment will be transitioned to shader read at render pass end
```

Sampling from wrong layout is invalid and will cause corruptions.

**Comment by SaschaWillems** [comment]
Thx for pointing this out. I thought that this would be in line with the spec, esp. as this does not trigger any validation message and is working for me on NVIDIA, AMD and Intel (Windows).

If this is indeed wrong (will take a look at that in detail) this may have to be fixed in several of my examples.
