### ISSUE TITLE
Error occurs when call vkCmdDispatch function in buildComputeCommandBuffer

### ISSUE THREAD

**Issue by yuchengzhong** [SaschaWillems/Vulkan#258]
Hello.Ive been learning vulkan with your examples' help for a long time.Your code is pretty good,and works well.
But in your older edition, raytracing doesnt work.
I enabled the validation,and found that when program called vkCmdDispatch,it would sent a message "trying to get mem binding for object 0x......  but no such object in buffer list.".
How can I solve this problem?Ive check my code for a long time but still find nothing wrong in the code.

Looking forward to your reply.Thanks.

**Comment by SaschaWillems** [comment]
Hard to tell without actual details. Which revision is the old code based on? I have reworked the raytracing example, so the current code differs a lot from the initial one.

The validation message seems to hint at a buffer not being filled. Since the validation message also shows you the pointer for that buffer object, you should be able to find out what buffer this is with the help of the debugger and then see why it isn't properly filled.

**Comment by yuchengzhong** [comment]
Thanks for your reply.How can I find the buffer via its pointer?Ive tried to do in vs,but can only get the value of it instead of finding its exactly position.
And the date of vk example in my computer is 2016.4.12.
Looking forward to your reply.Thanks.

**Comment by SaschaWillems** [comment]
Usually the validation message tells you the handle of the vulkan object . Set a break point for that validation error to occur and compare that handle (0xabc...) with the object handles you created to see what buffer object is causing this validation. 

Judging by the message I guess you forgot to call ```vkBindBufferMemory``` for one of the buffers you're using for compute.
