### ISSUE TITLE
cpu particlefire don't have fire on linux

### ISSUE THREAD

**Issue by git6721** [SaschaWillems/Vulkan#291]
![qq 20170224174541](https://cloud.githubusercontent.com/assets/15853042/23299122/3daf7db0-fabb-11e6-977c-a31cddc3f87a.png)

**Comment by SaschaWillems** [comment]
The example works fine on several Linux machines I have tested.

So please add some details. At least GPU, driver, distro, etc. and check validation layer output.

Judging by the screenshot I'm pretty sure that the GPU or driver doesn't emit correct point sprite UV coordinates.

**Comment by git6721** [comment]
Intel(R) HD Graphics 520 (Skylake GT2)
driver=i915_bpo
ubuntu16.04
no error with validation layer

**Comment by SaschaWillems** [comment]
If it's an Intel IGP I'm pretty sure it's because the driver does not generate proper uv coordinates for the point sprites. You can simple check this by disabling blending for the particles and changing the particle fragment shader to output uv coordinates. If you get solid black quads it's a driver problem.

**Comment by git6721** [comment]
i disable blending for the particle and only change this code "outFragColor.rgb = color.rgb * inColor.rgb;// * alpha;	" ,then get solid black quads.it's could see  as a dirver problem?

**Comment by SaschaWillems** [comment]
Yes, see e.g. #121. The example (and shaders) are fine, the problem is caused by the driver.
