### ISSUE TITLE
a problem about the usage of occlusion query

### ISSUE THREAD

**Issue by leihonh** [SaschaWillems/Vulkan#298]
Hi,Willems

![b w74 t1k11 01n 2 4qca](https://cloud.githubusercontent.com/assets/15853042/23651165/9ae089be-035f-11e7-8260-be9d268b0eb5.png)

Can you tell me what's it means with above image,because i move Occluder drawing codes from the first drawing toward the last drawing in your demos(occlusion query), but the object behind occluder could be seen, the rendering as below:
![ss](https://cloud.githubusercontent.com/assets/15853042/23651167/9d7ce2da-035f-11e7-8858-bfa8a01c9443.png)

**Comment by SaschaWillems** [comment]
The occluded object should be displayed with a different color (gray) if completely behind the occluder. If that's not the case then the occlusion query won't work.

But can you elaborate a bit? Your description makes it hard to find out what your actual problem is. Is the example not working at all for you, or did it stop working after you made changes?

**Comment by leihonh** [comment]
i move the occluder drawing codes at the end, behind the sphere and teapot,

according the note which i provide with the first picture,i think the final image should be occluded too,but it could be seen,

so,i don't understand the note from the first picture which i provided

**Comment by leihonh** [comment]
i know what's problem i encounter,thx
