### ISSUE TITLE
"subpasses" crashes when maximized (vkQueueWaitIdle returns ERROR_DEVICE_LOST)

### ISSUE THREAD

**Issue by amesgames** [SaschaWillems/Vulkan#414]
Really nice job on this project. Very polished and of professional quality.

**Comment by amesgames** [comment]
This occurs on Windows 10.

**Comment by SaschaWillems** [comment]
Are you running on a nvidia gpu? If so, there is a bug in the current drivers that causes this behaviour. If it's a different vendor please post the device you're using.

**Comment by SaschaWillems** [comment]
Afaik nvidia doesn't have a public issue tracker. I mailed this issue to one of vulkan contacts there some time ago and got confirmation that they intend to fix it.

**Comment by JacobHeAMD** [comment]
This issue is because attachments other than attachment[0] for swapchain image and attachment[4] for depth are not updated while resizing window. As a consequence, the width and height of all attachments are not identical. VMfault happens when Gpu access the memory allocated with old width/height.
Subpasses possilby can overwrite windowResize() (make it virtual first certainly) to destroy the old attachments.position, attachments.normal, attachments.albedo and create new one before setup new frame buffer with destWidth and destHeight. What's a little bit more complicated is the resources depends on attachments.position/normal/albedo should be re-allocated with new width and height as well.

**Comment by JacobHeAMD** [comment]
@SaschaWillems , could you please help to fix it?

**Comment by SaschaWillems** [comment]
Please check again. I have updated the sample to properly handle resizes.

**Comment by JacobHeAMD** [comment]
@SaschaWillems , issue is not seen with the latest code

**Comment by JacobHeAMD** [comment]
Thanks!
