### ISSUE TITLE
-- Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR)

### ISSUE THREAD

**Issue by Spacebody** [SaschaWillems/Vulkan#428]
I am installing glfw on macOS 10.12.6 and I need to install Vulkan following with the installation on your website. But I encounter such problem and could not find a solution so how can I set the variables so that these two missing variables can be fixed?

**Comment by SaschaWillems** [comment]
Can you elaborate? My examples don't use glfw.

**Comment by Spacebody** [comment]
@SaschaWillems Sorry. The problem is that I have not correctly install vulkan through source code so that when glfw try to retrieve these two variables it can not find. I had installed vulkan by following the guide of your website, then I don't know what is the problem then?

**Comment by SaschaWillems** [comment]
My examples (this is not an official Vulkan repo!) take these from either an installed Vulkan SDK (if VULKAN_SDK environment variable is set), or (if this is not present) from the local paths of the examples. 

How are you trying to build and when does the error occur? Are you using a current CMake version to generate the build files?

**Comment by Spacebody** [comment]
Yes, I am using the current CMake version.

**Comment by SaschaWillems** [comment]
Then you have to set these manually. VULKAN_LIBRARY needs to point to the vulkan library file for your platform, which is included in the SDK (and not in my examples for osx), VULKAN_INCLUDE_DIR needs to point to the include directory that contains vulkan.h.

**Comment by Spacebody** [comment]
For macOS platform, which library file should VULKAN_LIBRARY to point to or just point to the folder ```lib``` in ```macOS```?

**Comment by SaschaWillems** [comment]
I don't own any Apple devices so I haven't tested myself, but I guess you've got a library folder with a vulkan-1.lib somewhere in the SDK. The VULKAN_LIBRARY path needs to point to that directory.

**Comment by Spacebody** [comment]
I find .dylib file and I think that it is. Thank you.

**Comment by AbhinavAdarsh** [comment]
@Spacebody I am facing the same issue. Could you tell me what changes did you do in your CMakeLists.txt. I am unable to set the path.

**Comment by Spacebody** [comment]
@AbhinavAdarsh I find the path but it seems the warnings didn't make any bad effects, so I just left it be.

**Comment by dkgaraujo** [comment]
Hi all! What I did to successfully install vulkan on a mac was to tinker a bit with the `install_vulkan.py` file. Basically what is does is that it reads a JSON list of files and directories and their intended destination in your local system, and then copies them (or creates a link to the original files) accordingly. For me, the `missing Vulkan_LIBRARY Vulkan_INCLUDE_DIR` error was occurring because I had not run the `install_vulkan.py` file I mentioned above. But when I ran it out of the box, it would always return errors. So I discovered it was simply because it was not reading the directory for the `INSTALL_BOM.json` file and then of the files to be installed correctly. 

So first, I used the `--install-json-location` argument when calling the installation script; second, I included a new line in the python script with the actual base folder of where the VulkanSDK was downloaded, as below:
` base_folder = "/Users/yourusernamehere/Coding/VulkanSDK"` 

And finally, I changed the following code line (the commented one is the original, my adjustment is the uncommented one):

```#abspath_key = os.path.abspath(key)
        abspath_key = base_folder + key[1:]```

Then it worked like a charm. Hope the above can be helpful to you as well.

**Comment by zoldaten** [comment]
hi!
i have vulkan installed on raspberry pi 4 (Raspbian Bullseye):
![2024-11-21_11h29_08](https://github.com/user-attachments/assets/79dce2b0-2643-43e0-9395-4ad4ea6b0282)

![2024-11-21_11h32_59](https://github.com/user-attachments/assets/4f3d88c3-38e1-44c0-989e-746fddf71ff3)

how to taste your examples as i see trying to build ?:
![2024-11-21_11h33_33](https://github.com/user-attachments/assets/ceaf6e51-9c31-407e-b44f-1ef0c7e358e1)

i tried export paths:
export Vulkan_LIBRARY="/usr/lib/aarch64-linux-gnu/libvulkan.so.1"
export Vulkan_INCLUDE_DIR="/home/pi/mesa_vulkan/include/vulkan"

may be wrong way?

**Comment by SaschaWillems** [comment]
Your output is missing the actual lubvulkan.so:

![image](https://github.com/user-attachments/assets/f7b3cb3f-5451-4103-9c35-70aeaf987c86)

**Comment by zoldaten** [comment]
![2024-11-21_12h52_19](https://github.com/user-attachments/assets/a3c228a4-f875-476f-abed-1b85e5de44ea)

built from source.

**Comment by zoldaten** [comment]
dont think so. 
may be my exports wrong ?
```
export Vulkan_LIBRARY="/usr/lib/aarch64-linux-gnu/libvulkan.so.1"
export Vulkan_INCLUDE_DIR="/home/pi/mesa_vulkan/include/vulkan"
```

**Comment by SaschaWillems** [comment]
I don't have that much experience with Linux, but I guess the issue is the .1. Try to rename it to libvulkan.so?

**Comment by zoldaten** [comment]
didnt help ((
at the same time i built examples https://github.com/KhronosGroup/Vulkan-Samples/blob/main/docs/build.adoc#linux :
![2024-11-21_15h21_25](https://github.com/user-attachments/assets/891fe786-ae10-415c-a3e5-eef2c0d0173a)

**Comment by SaschaWillems** [comment]
The Khronos samples use a different build setup. But if those works, go ahead and use those instead.

**Comment by gl2007** [comment]
> Hi all! What I did to successfully install vulkan on a mac was to tinker a bit with the `install_vulkan.py` file. 
where is this located? Couldn't find any such file in my vulcan sdk install folder

**Comment by JakubK** [comment]
I have encountered similar issue today, had to install `vulkan-loader-devel` package
