### ISSUE TITLE
Demos are crashing when window is minimized

### ISSUE THREAD

**Issue by mmostajab** [SaschaWillems/Vulkan#493]
Is it already known that all the demos are crashing when we minimize the window? I am testing the demos on my NVIDIA GTX 980.

**Comment by SaschaWillems** [comment]
Yes, I'm aware of it and the issue still seems to be present in current nvidia drivers. At least for the Vulkan developer drivers.

**Comment by Cry-Mory** [comment]
Are they aware of it? Maybe we can open a bug report.

**Comment by SaschaWillems** [comment]
Yes, I have forwarded this some time ago.I don't think this has a high priority for them. There's also a workaround for this that I'll try to add when time permits.

**Comment by SaschaWillems** [comment]
I have pushed two small changes. No more rendering if minimized and check if swap chain gets out of date. With these the samples should no longer crash when minimizing the window on Windows.

**Comment by YukinoHayakawa** [comment]
> No more rendering if minimized and check if swap chain gets out of date. 

This is critical. I thought I had to recreate the device and do a lot of things etc etc when I found this problem. Turned out that I only have to wait device idle and pause the rendering. When the window is restored the device can be used as usual like nothing has happened : )

**Comment by Ziflin** [comment]
In my code I noticed that I get a Validation Error `VUID-vkAcquireNextImageKHR-semaphore-01779` after un-minimizing a Vulkan window on Windows (AMD GPU) in my call to `vkAcquireNextImageKhr()`. As @YukinoHayakawa mentioned, this is fixed by call `vkDeviceWaitIdle()` during the WM_SIZE handler if the window state is now Minimized.

I was just curious as to what is happening? It appears that all that is needed is just the device wait and no swapchain recreation is required. (I currently don't recreate/resize the swapchain to a size of 1,1 when minimizing which some other tutorials may do which hides the issue.)
