### ISSUE TITLE
Problem building sameples with MinGW-64

### ISSUE THREAD

**Issue by ethan-tqa** [SaschaWillems/Vulkan#51]
The problem is the generated binaries looks for libassimp.dll, and if I rename the dll that comes with the source, it would throw an error saying "... entry point _Z6Assimp8Importer8ReadFileEPKcj could not be located..."

**Comment by SaschaWillems** [comment]
I tested with Visual Studio 2015 and MinGW (64-Bit) on Windows, and both compile and run the samples fine.

It's possible that you have to compile assimp yourself depending on your compiler.

**Comment by ethan-tqa** [comment]
Not sure if it makes any difference, but i'm opening the project and compiling from within Qt Creator

**Comment by SaschaWillems** [comment]
Haven't tested my examples with Qt Creator. What operating system are you on? If you're on linux you may have to delete the assimp libraries included (wrong target), and install assimp globally.

**Comment by ethan-tqa** [comment]
I'm using windows 10, 64-bit MinGW from msys. As a matter of fact I tried various set up of MinGW, Qt creator and CLion but no luck so far. Default 32-bit GCC from Qt can't even solve some symbols, like vkDestroyBuffer@16, probably because it was using the 64-bit lib. Everything works fine with VS 2015 on the same machine.

**Comment by ethan-tqa** [comment]
I checked the output from cmake, it is using libassimp.dll.a instead of assimp.lib

**Comment by SaschaWillems** [comment]
> Also why is the file 16 MB?
Probably because it's a debug build.

I guess it's not compatible with the linker (compiler) you're using. Can you try building assimp with your compiler and using that lib instead of the one provided?

**Comment by Squareys** [comment]
> Default 32-bit GCC from Qt can't even solve some symbols, like vkDestroyBuffer@16, probably because it was using the 64-bit lib.

Thanks! That was indeed a problem, 32bit libs are provided in `VulkanSDK/<version>/Bin32/`.
(Quick naive workaround could be `string(REPLACE "Bin/" "Bin32/" VULKAN_LIB ${VULKAN_LIB})` in L26 for example)

As for the assimp library, recompiling it yourself and using that will most likely work?

**Comment by SaschaWillems** [comment]
> PS: I might create a pullrequest for MinGW support sometime next week, if nobody else beats me to it.

At least on windows, the examples compile fine with MingW. Before comitting changes I usually test with the VS2015 and MingW compilers on windows.

**Comment by Squareys** [comment]
> > [...] pullrequest for MinGW support [...]

> At least on windows, the examples compile fine with MingW. [...]

@SaschaWillems Sorry, I probably phrased that badly. I did notice from the `libassimp.dll.a` that there is support for MinGW.
I guess this might just be a small issue regarding 32bit vs 64bit libraries or possibly incompatibility of MinGW <-> MinGW-w64 libraries (libassimp.dll.a)?

Are you using MinGW-w64?
I use i686-w64-mingw32 (gcc 5.1.0, posix, dwarf) On Win10 64bit. CMake correctly found my VulkanSDK installation, but 64bit libraries instead of the 32bit ones (which would have matched the compiler), and had some linking issues with assimp. I was able to solve the first with that workaround and the latter by recompiling assimp myself. I tried the triangle example and it compiles and runs perfectly fine now.
