### ISSUE TITLE
[Requirement] Example for VK_EXT_transform_feedback

### ISSUE THREAD

**Issue by ghostplant** [SaschaWillems/Vulkan#573]
It is a new feature since Vulkan 1.1.88, used for many games that have feedback requirement.
Eager to share such an example for this extension.

**Comment by SaschaWillems** [comment]
Transform feedback was only added to Vulkan for back-wards compatibility with older titles, esp. in regards to DXVK and is something that would have otherwise never been added to Vulkan, see [this article on why](http://jason-blog.jlekstrand.net/2018/10/transform-feedback-is-terrible-so-why.html). As such I don't have any plans to add an example for it.
