### ISSUE TITLE
Old problems still exists. void VulkanExample::draw(): Assertion `res == VK_SUCCESS' failed.

### ISSUE THREAD

**Issue by engineer1109** [SaschaWillems/Vulkan#594]
For the triangle.cpp crashing on the resizing the window.
void VulkanExample::draw(): Assertion `res == VK_SUCCESS' failed.
Fatal : VkResult is "ERROR_OUT_OF_DATE_KHR" in /home/wjl/projects/Vulkan/examples/triangle/triangle.cpp at line 358
triangle: /home/wjl/projects/Vulkan/examples/triangle/triangle.cpp:358: void VulkanExample::draw(): Assertion `res == VK_SUCCESS' failed.
Hardware:
Nvidia 430.26  RTX2070 Max Q
Intel I9-8950HQ
Software:
Ubuntu 18.04.02LTS 
kernel 4.18.17

**Comment by engineer1109** [comment]
Vulkan version 1.108

**Comment by pianofingers** [comment]
Fresh install of Ubuntu 20.04, default drivers (nvidia-driver-440). NVIDIA GTX 1080. Resizing the triangle example I get:
```
Fatal : VkResult is "ERROR_OUT_OF_DATE_KHR" in /home/orri/Vulkan/examples/triangle/triangle.cpp at line 363
triangle: /home/orri/Vulkan/examples/triangle/triangle.cpp:363: void VulkanExample::draw(): Assertion `res == VK_SUCCESS' failed.
Aborted (core dumped)
```

Due to the abysmal state of Linux I use this project as a sanity check to see if Vulkan is working correctly (because nothing can be trusted to work) before I work on my vulkan projects. It's not exactly a good sign when even this project, with its 1800+ commits can't even run correctly as it instantly crashes when resizing the triangle demo's window. I don't know why this project asserts instead of handling the out of date error, since it can happen according to the spec, maybe it's assuming that it's handled differently elsewhere, but clearly it's not.

**Comment by pianofingers** [comment]
Fresh install of Ubuntu 20.04, default drivers (nvidia-driver-440). NVIDIA GTX 1080. Resizing the triangle example I get:
```
Fatal : VkResult is "ERROR_OUT_OF_DATE_KHR" in /home/orri/Vulkan/examples/triangle/triangle.cpp at line 363
triangle: /home/user/Vulkan/examples/triangle/triangle.cpp:363: void VulkanExample::draw(): Assertion `res == VK_SUCCESS' failed.
Aborted (core dumped)
```

Due to the abysmal state of Linux I use this project as a sanity check to see if Vulkan is working correctly (because nothing can be trusted to work) before I work on my vulkan projects. It's not exactly a good sign when even this project, with its 1800+ commits can't even run correctly as it instantly crashes when resizing the triangle demo's window. I don't know why this project asserts instead of handling the out of date error, since it can happen according to the spec, maybe it's assuming that it's handled differently elsewhere, but clearly it's not.

**Comment by pianofingers** [comment]
Fresh install of Ubuntu 20.04, default drivers (nvidia-driver-440). NVIDIA GTX 1080. When resizing the triangle window I instantly get this error:
```

Fatal : VkResult is "ERROR_OUT_OF_DATE_KHR" in /home/user/Vulkan/examples/triangle/triangle.cpp at line 363
triangle: /home/user/Vulkan/examples/triangle/triangle.cpp:363: void VulkanExample::draw(): Assertion `res == VK_SUCCESS' failed.
Aborted (core dumped)
```

I use this project as a sanity check to see if Vulkan is even working on the system, before I work on my own Vulkan projects. It doesn't exactly inspire confidence in Vulkan and Linux when even this project gets things wrong, with its 1800+ commits. Is it assuming that the out of date error can't happen because it's somehow handled elsewhere differently?

**Comment by SaschaWillems** [comment]
OUT_OF_DATE is handled for all other examples in the example base class. The triangle one doesn't handle it because I wanted to keep it simple. But feel free to add this as a PR.

**Comment by pianofingers** [comment]
Oh alright, sorry I'm having a frustrating day with my Linux system! Also sorry for deleting my comment twice, I accidentally included my username which is my name and I wanted to keep that out.

**Comment by SaschaWillems** [comment]
No problem, I've had my fair share of frustrating issues with Linux, both here on my private stuff as well as at work ;)
