### ISSUE TITLE
ImGui:keyboard input not work on win10 1803,gtx1060

### ISSUE THREAD

**Issue by Iteravse** [SaschaWillems/Vulkan#618]
what ever i typing any word  in inputs ,number or words,type in console,it stil not work,but mouse event seems work well,and i conjecture that keyboard event can't trigger,but i can't see any error in ImGui example.in tab of 'Inputs Navigation & Focus',the key event never trigger when i press,why it donsn't work,and how to solve this problem?(thanks for these example a lot:)
![image](https://user-images.githubusercontent.com/34048239/65373231-50872d80-dcad-11e9-923f-ce3f136e396f.png)

**Comment by SaschaWillems** [comment]
Keyboard input is not implemented for that sample, that's why it's not working.

**Comment by Iteravse** [comment]
> Keyboard input is not implemented for that sample, that's why it's not working.

so how can i implement it,or any implemented demo project recommend?  I've been looking for a suitable realize input method typing with valkan C++ for longtime ago

**Comment by engineer1109** [comment]
linux also cannot work

**Comment by Iteravse** [comment]
> linux also cannot work

but i'm using win10,it's normalcy?

**Comment by engineer1109** [comment]
@Iteravse Because the author dont write the code dealing the keyboard focus, and it confilcts with other keyboard event like WASD and space. The keyboard still focus the main window. For this problem, the linux solution is to rewrite the code of keyboard event. Override-redirect the X-Window. When your mouse click the textline, focus the Xwindow on the textline.
Win10 is not a unix and posix stardard system, cannot use Xwindow directyly except Cygwin. For win32 solution, you need to help yourself.

**Comment by SaschaWillems** [comment]
The official [ImGui repository](https://github.com/ocornut/imgui) contains a Vulkan example where keyboard input is fully working by using either glfw or sdl. If you need a reference you may take a look at it.
