### ISSUE TITLE
Multiview sample does not work on 1.1 device without VK_KHR_multiview

### ISSUE THREAD

**Issue by chrisforbes** [SaschaWillems/Vulkan#633]
This extension was promoted to core, and there are various implementations which support *only* the core version.

There seems to be no precedent for samples doing something different in a 1.1 environment though, so unsure how you want to do this.

**Comment by SaschaWillems** [comment]
Not sure how to tackle this either. I could check if the implementation supports VK 1.1 and up and then just go ahead with the core functionality instead of the extension one.

**Comment by SaschaWillems** [comment]
I tried to wrap my head around this, but it's a bit like a chicken egg problem. In order to add a switch I'd need to know the api version of the device. But in order to create the device I need to know what extensions to add. Changing this would require a lot of rework, so I'll probably won't be able to fix this in my samples.
