### ISSUE TITLE
raytracingShadows example - VulkanExampleBase::bool resized is not reset

### ISSUE THREAD

**Issue by kyamant** [SaschaWillems/Vulkan#980]
Once the variable `VulkanExampleBase::bool resized` is set in `VulkanExampleBase::windowResize()`, it does not get reset (for example in `VulkanExample::handleResize()` or at the end of `VulkanExampleBase::windowResize()`).
A resizing of the window results in `VulkanExample::handleResize()` being called every frame from then on.

**Comment by SRSaunders** [comment]
This is a good catch, and applies to the raytracingbasic, raytracingcallable, raytracingreflections, raytracingshadows, and variablerateshading examples, where `VulkanExample::handleResize()` is called to recreate the image (and descriptor) prior to rebuilding the command buffers.  It's great that you found this defect, especially since these are examples I could not test as part of my recent changes for macOS/iOS (including resizing for all platforms) due to lack of support from my graphics card and MoltenVK.

For other examples (i.e. multiview, oit) the virtual function `VulkanExample::windowResized()` is implemented for custom resize handling and clears the `resized` flag prior to rebuilding the command buffers for the derived class.  Implementing the virtual function `VulkanExample::windowResized()` simply to clear the `resized` flag for the above 5 examples seems like overkill, unless custom resize handling is required for some reason (I am not certain since I can't test them).

As you mention above, and assuming customized resize handling is not needed, it probably makes sense to clear the flag at the end of the `VulkanExampleBase::windowResize()` function.  This will guarantee the flag is cleared at the end of the same code block in which it is set: 

```
// Notify derived class
windowResized();
viewChanged();

prepared = true;
resized = false;
```

**Comment by SaschaWillems** [comment]
Thanks for bringing this up. This is indeed a bug that'll try to fix asap.
